default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: <%= ENV.fetch("DATABASE_NAME", "rails-ralix-tailwind_development")  %>
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "rails-ralix-tailwind_test")  %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "rails-ralix-tailwind_production")  %>
