default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: <%= ENV.fetch("DATABASE_NAME", "puffintours_development")  %>
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "puffintours_test")  %>

production:
  <<: *default
  host:     <%= ENV.fetch("DATABASE_HOST", "1.2.3.4")  %>
  database: <%= ENV.fetch("DATABASE_NAME", "puffintours_production")  %>
  username: <%= ENV.fetch("DATABASE_USER", "puffintours_produser")  %>
  password: <%= ENV.fetch("DATABASE_PASS", "YouReallyWishItWasThatEasyUh?")  %>
