test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>


# In Cloud run l'autenticazione e' gratuita.
# In locale serve `private/puffin-tours-secret-key.json`

google: &gcs
  service: GCS
  bucket: puffin-tours-public
  credentials: <%= File.exist?('private/puffin-tours-secret-key.json') ? 'private/puffin-tours-secret-key.json' : nil %>
  project: "puffin-tours"
  public: true
  cache_control: "public, max-age=3600"

  #client_email: <%= File.exist?('private/puffin-tours-secret-key.json') ? "puffintours-app-storager@puffin-tours.iam.gserviceaccount.com" : nil %>
  #cache_control: "public, max-age=3600"
  #credentials: <%= Rails.root.join("path/to/keyfile.json") %>
  # in PROD/Docker I need to remove this, dammit. JHow do I say "dont use this?!? LEts try just removing it"
  #credentials: private/puffin-tours-secret-key.json

local:
  <<: *gcs
  #service: Disk
  #root: <%= Rails.root.join("storage") %>
