test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>


# In Cloud run l'autenticazione e' gratuita.
# In locale serve `private/puffin-tours-secret-key.json`

gcs: &gcs
  service: GCS
  project: puffin-tours
  credentials: <%= Rails.root.join("private/puffin-tours-secret-key.json") %>
  bucket: puffin-tours-public
  credentials: <%= File.exist?('private/puffin-tours-secret-key.json') ? 'private/puffin-tours-secret-key.json' : nil %>
  project: "puffin-tours"
  public: true

# If you want a different config for development/production:
development:
  <<: *gcs

production:
  <<: *gcs

local:
  <<: *gcs
  #service: Disk
  #root: <%= Rails.root.join("storage") %>
